# Generated by Django 4.2.4 on 2023-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
    ]
