# Generated by Django 4.2.4 on 2023-08-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
    ]
